name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [self-hosted, linux, ARM]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'development'
    - name: prepare
      run: mkdir cmake_link
    - name: configure
      run: cmake ..
      working-directory: cmake_link
    - name: make
      run: make -j4
      working-directory: cmake_link

